language: node_js

cache:
  apt: true
  directories:
    - node_modules

node_js: stable

install:
  - npm install -S
  - cd ./test/smoke/template
  - npm install -S
  - cd ../../../

script:
  - npm run test